language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_e3ce7c39c37e_key -iv $encrypted_e3ce7c39c37e_iv
  -in environment.tar.enc -out environment.tar -d
- tar xvf environment.tar -C sharedlock
script:
- ./gradlew test
after_success:
- ./gradlew uploadArchives
